<a href="https://colab.research.google.com/github/elnrdfrs/article_frontiers_notebook/blob/main/csv_concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import os
#from pandas_profiling import ProfileReport
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown as md
import glob
import pandas as pd

In [20]:
to_concat = glob.glob('*.csv')

df_c = pd.read_csv(to_concat[0], sep=';')
for f in to_concat[1:]:
  df_c = pd.concat([df_c, pd.read_csv(f, sep=';')])
  df_c = df_c.drop_duplicates(subset = ["OriginDataset", "Algorithm", "patientId", "Lambda1", "Lambda2", "Lambda3"])
df_c[["Dice", "Dice_anima", "sens", "OriginDataset", "Algorithm"]]
#to_concat

        Dice  Dice_anima    sens OriginDataset   Algorithm
0   0.126779    0.126779  direct         MSSEG      affine
1   0.000000    0.000000  direct         MSSEG      affine
2   0.000000    0.000000  direct         MSSEG      affine
3   0.000000    0.000000  direct         MSSEG      affine
4   0.000802    0.000802  direct         MSSEG      affine
..       ...         ...     ...           ...         ...
15  0.000000         NaN  direct         MSSEG  sequential
24  0.000000         NaN  direct         MSSEG  sequential
69  0.000000         NaN  direct         MSSEG  sequential
75  0.556491    0.556047  direct         MSSEG  sequential
83  0.006410    0.006397  direct         MSSEG  sequential

[718 rows x 5 columns]

In [19]:
df_c.to_csv('res/concat_anima_v4.csv', sep=',')